### ISSUE TITLE
NoSuchMethodError exception thrown when using Katharsis with jackson 2.7

### ISSUE THREAD

**Issue by barabanger** [katharsis-project/katharsis-framework#73]
It appears that unless katharsis-framework specifically compiled with `<jackson.version>2.7.6</jackson.version>` set in pom.xml it will crash with following message:

`
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedField.<init>(Lcom/fasterxml/jackson/databind/introspect/AnnotatedClass;Ljava/lang/reflect/Field;Lcom/fasterxml/jackson/databind/introspect/AnnotationMap;)V
	at io.katharsis.resource.field.ResourceFieldNameTransformer.getName(ResourceFieldNameTransformer.java:41)
`

**Comment by danielmischler** [comment]
Isn't this a regression?

I  thought that this was fixed in context with the Kebab PropertyNamingStrategy issue.

I have to admit that I never got to work it properly in my projects.
Since katharsis uses jackson 2.6.3 I kept using a very old version of dropwizard (0.8.4) and by-passed the kebab-case functionality.

But it's definitely time to upgrade several framworks that *all* use jackson 2.7.x (currently jackson is on 2.8.1), e.g. dropwizard (1.0.0), neo4j-ogm (2.0.4), etc.

What's the reason to not use 2.7.x for katharsis?

**Comment by meshuga** [comment]
With which Jackson version this error occurs?

Katharsis should be working with Jackson 2.7, but it might be a good idea to switch to newer version.

**Comment by barabanger** [comment]
Jackson version 2.7.6 (used by Dropwizard 1.0.0). 
I can see that work around code in Katharsis for Jackson 2.7 AnnotatedClass builder is being called, but still unless Katharsis itself compiled with 2.7 Jackson it was crashing. Also, at least for me it required to delete Katharsis target folder  in order for this bug to appear  once I started to switch between 2.7 & 2.6.

**Comment by meshuga** [comment]
I'm now also getting this error. We adjusted Katharsis to be working with version 2.7.3 as far as I remember. I think it might be good idea to switch to a newer version, but now I need to investigate why  this error doesn't occur when you compile Katharsis with newer version, it's strange.

**Comment by meshuga** [comment]
I'm stupid. They changed the `AnnotatedField` constructor. Before the first parameter was of type `AnnotatedClass` but now it's an interface which `AnnotatedClass` implements, that is `TypeResolutionContext`. I'll make Katharsis to be agnostic when it comes to that.

Additionally, I'll update the Katharsis version to 2.7.6.

**Comment by barabanger** [comment]
Awesome!
Thanks

**Comment by meshuga** [comment]
Thanks for the issue! It's a good lesson that each change (even the most simplistic one) might result in a serious problem. In this case probably https://github.com/FasterXML/jackson-databind/issues/983 was the reason it had been done ;)
